version: "3.8"

services:
  api:
      image: orders_api:latest
      ports:
        - "8000:8000"
      command: uvicorn --reload --host 0.0.0.0 --port 8000 orders_api.main:app
      volumes:
        - .:/workspace:z
