"""add more columns to stores table

Revision ID: 7b26eb4c5d78
Revises: 5cb03acc4439
Create Date: 2021-01-05 17:57:59.807686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b26eb4c5d78'
down_revision = '5cb03acc4439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('domain', sa.Text(), nullable=True))
    op.add_column('stores', sa.Column('phone', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'phone')
    op.drop_column('stores', 'domain')
    # ### end Alembic commands ###
